### ISSUE TITLE
More rendering engines

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#386]
Support for additional *real* rendering engines such as Safari, Firefox, Chrome, iOS Safari, and others.  

Technically, Tandem would communicate with a back-end service which would spin up these browsers, and send a video feed of the application preview against the target browser.

**Comment by tomByrer** [comment]
I don't think it needs to be 'built in' much further than (BrowserSync)[https://browsersync.io/] for right now.

**Comment by crcn** [comment]
@tomByrer Yeah, I think that something like BrowserSync will work in most cases. Though something like a Browserstack / Sauce Labs / BrowserTap (personal project) integration would be nice to have to cover devices & browser versions that the user might not have. 

Closing in favor of #395.
