### ISSUE TITLE
Webpack dependency graph strategy

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#387]
Should significantly speed up preview reloads in Tandem. This would enable Tandem to automatically reload applications that use [Webpack](webpack.js.org) *as the developer is typing*.

**Comment by tomByrer** [comment]
Maybe with adjustable throttling?

**Comment by crcn** [comment]
Yep, throttling already exists under the hood, so a Webpack dependency graph strategy would use this functionality out of the box.

**Comment by crcn** [comment]
Flagged as completed since the newer version of Tandem allows for Webpack + HMR to be used in the app. A webpack dependency graph strategy is no longer necessary.
