### ISSUE TITLE
Alpha » HTML Inspector

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#402]
Parent: #409

Basically the equivalent to Sketch layers. 

#### Legend

⬜️ - Hasn't started
📝 - In Progress
✅ - Complete (merged into `dev`)

#### General
Issue | PR | Feature | Progress |
|:----:|:----:|:--------|:----:|
| ???? | ???? | right click inspect element | ⬜️ |
| ???? | ???? | HTML breadcrumbs | ⬜️ |
| ???? | ???? | see rendered HTML (not editable) | ⬜️ |
| ???? | ???? | right click node & see source code | ⬜️ |
| ???? | ???? | highlight selected nodes| ⬜️ |

**Comment by tomByrer** [comment]
Hmmm, web devs can be attached to their editors (config, intellisense, highliters, linters).  I'm not sure if you're ready to open Pandora's Box yet.... you'll see an endless stream of requests & bug reports on this feature alone.

Maybe at most a `Edit this` button which will open said files in an editor.  But then, how will you handle imports, both of parents & children?

**Comment by crcn** [comment]
@tomByrer I agree that an HTML inspector would be a bit of a Pandora's box. I'm imagining the initial version of this will be read-only, allowing developers to _only_ see the rendered HTML of their application for debugging purposes. From there, we can explore ways of adding visual editing tools from the inspector itself (if it's possible).
