### ISSUE TITLE
Not Running on Windows Subsystem Linux

### ISSUE THREAD

**Issue by matbrgz** [crcn/tandem-old#408]
Microsoft Windows [Version 10.0.15063]

`# nvm list
         v0.7.4
->       v7.4.0
         v7.9.0
default -> node (-> v7.9.0)
node -> stable (-> v7.9.0) (default)
stable -> 7.9 (-> v7.9.0) (default)
unstable -> 0.7 (-> v0.7.4) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.3 (-> N/A)
lts/boron -> v6.10.3 (-> N/A)`

`# npm version
{ tandemapp: '1.0.5',
  npm: '4.0.5',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.4.0',
  openssl: '1.0.2j',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.45',
  zlib: '1.2.8' }`

`#npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

**when instaling**

`# WATCH=1 npm run build
 tandemapp@1.0.5 build /mnt/c/Users/mathe/Dev/tandem-master
 gulp build

[04:13:47] Using gulpfile /mnt/c/Users/mathe/Dev/tandem-master/gulpfile.js
[04:13:47] Starting 'build'...
[04:13:47] Starting 'prepare'...
[04:13:47] Starting 'prepare:copy-d-ts-assets'...
[04:13:47] Finished 'prepare:copy-d-ts-assets' after 487 ms
[04:13:47] Starting 'prepare:copy-assets'...
[04:14:01] Finished 'prepare:copy-assets' after 14 s
[04:14:01] Starting 'prepare:mono-package'...
[04:14:01] Starting 'prepare:create-mono-package'...
[04:14:01] Finished 'prepare:create-mono-package' after 11 ms
[04:14:01] Starting 'clean:symlinks'...
[04:14:01] Finished 'clean:symlinks' after 99 ms
[04:14:01] Starting 'prepare:install-mono-package'...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-file-input@0.2.5 requires a peer of react@0.x but none was installed.
npm WARN out No repository field.
npm WARN out No license field.
[04:14:15] Finished 'prepare:install-mono-package' after 14 s
[04:14:15] Finished 'prepare:mono-package' after 14 s
[04:14:15] Finished 'prepare' after 28 s
[04:14:15] Starting 'build:peg'...
[04:14:16] Finished 'build:peg' after 499 ms
[04:14:16] Starting 'build:typescript'...`

than...

![powershell_2017-06-01_01-10-57](https://cloud.githubusercontent.com/assets/23284276/26664350/38bb5ff2-4667-11e7-8dd7-64d45dabf0d8.png)

**Bottom Line**
`npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/root/.nvm/versions/node/v7.4.0/bin/node" "/root/.nvm/versions/node/v7.4.0/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! tandemapp@1.0.5 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tandemapp@1.0.5 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tandemapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tandemapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tandemapp
npm ERR! There is likely additional logging output above.`

**npm-debug.log**
`0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v7.4.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v7.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle tandemapp@1.0.5~prebuild: tandemapp@1.0.5
6 silly lifecycle tandemapp@1.0.5~prebuild: no script for prebuild, continuing
7 info lifecycle tandemapp@1.0.5~build: tandemapp@1.0.5
8 verbose lifecycle tandemapp@1.0.5~build: unsafe-perm in lifecycle true
9 verbose lifecycle tandemapp@1.0.5~build: PATH: /root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/bin/node-gyp-bin:/mnt/c/Users/mathe/Dev/tandem-master/node_modules/.bin:/root/.nvm/versions/node/v7.4.0/bin:~/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/Oracle/Java/javapath_target_73688921:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Users/mathe/AppData/Roaming/nvm:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/Users/mathe/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mathe/AppData/Roaming/nvm:/mnt/c/Users/mathe/AppData/Local/atom/bin
10 verbose lifecycle tandemapp@1.0.5~build: CWD: /mnt/c/Users/mathe/Dev/tandem-master
11 silly lifecycle tandemapp@1.0.5~build: Args: [ '-c', 'gulp build' ]
12 silly lifecycle tandemapp@1.0.5~build: Returned: code: 1  signal: null
13 info lifecycle tandemapp@1.0.5~build: Failed to exec build script
14 verbose stack Error: tandemapp@1.0.5 build: `gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid tandemapp@1.0.5
16 verbose cwd /mnt/c/Users/mathe/Dev/tandem-master
17 error Linux 4.4.0-43-Microsoft
18 error argv "/root/.nvm/versions/node/v7.4.0/bin/node" "/root/.nvm/versions/node/v7.4.0/bin/npm" "run" "build"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error tandemapp@1.0.5 build: `gulp build`
22 error Exit status 1
23 error Failed at the tandemapp@1.0.5 build script 'gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the tandemapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs tandemapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls tandemapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by crcn** [comment]
This should no longer be an issue with the newer version of Tandem. Closing for now.
