### ISSUE TITLE
While doing npm install i am getting below error

### ISSUE THREAD

**Issue by avinashdvv** [crcn/tandem-old#433]
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/crcn/gulp-atom-electron.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/crcn/gulp-atom-electron.git/' not found
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/veera/.npm/_logs/2018-04-15T10_03_37_639Z-debug.log

**Comment by crcn** [comment]
Tandem is still in flux right now, but I'm hoping to have an Alpha ready sometime in the next couple of months. I'll clean up the build scripts once it gets closer to that milestone. Closing this ticket for now.

**Comment by avinashdvv** [comment]
I would like to contribute to it. How can i do that?

**Comment by crcn** [comment]
Awesome! I'm really glad to hear that. I would really love help with the project, but right now the idea's a bit of a fog, so it's hard for me to tell you exactly how you could contribute _now_. However, after the app reaches Alpha and matures based on feedback, then I think it'd be safe for contributions. I can tell you a few things that I'm aiming for that could use some help in the future:

- Web framework targets (VueJS, AngularJS)
- Developer tooling (bundler integration, service hooks)
- Platform targets (iOS, Android)
- Tandem Extensions

☝️ I have no idea what these should will look like now, but they're definitely coming.

**Comment by avinashdvv** [comment]
Thanks for the reply. Once it reaches to Alpha, I will try to contribute to this project 👍 👍 👍
