### ISSUE TITLE
how to build and run it?

### ISSUE THREAD

**Issue by chenty** [crcn/tandem-old#434]

**Comment by crcn** [comment]
Tandem is still far from being usable, but I'll have instructions available for an Alpha version in the next couple of months.

**Comment by crcn** [comment]
Wanted to give you a heads up that a pre-release version is available now: https://github.com/crcn/tandem/releases/tag/untagged-8d77183feaf06c50f713

Keep in mind that the app is buggy. More fixes & features to come in a few weeks.
