### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#670]

**Comment by JasonTypesCodes** [comment]
Is there anything I can do to assist with this?  I've successfully built / ran Tandem Desktop in Fedora Linux from master with no modifications.  Are you hoping to make distro-specific packages?

![image](https://user-images.githubusercontent.com/1888131/55284967-ed908b80-5346-11e9-8f6b-0e50e1356f01.png)

**Comment by crcn** [comment]
> Are you hoping to make distro-specific packages?

Yeah, that's the goal. Shouldn't be more than a few hours, just haven't gotten around to building the scripts.

**Comment by crcn** [comment]
Closing this ticket in favor of #703.
