### ISSUE TITLE
windows build right click on main.pc in layers panel crashes the app

### ISSUE THREAD

**Issue by mapsgeek** [crcn/tandem-old#691]
![image](https://user-images.githubusercontent.com/10188264/52174196-44d80c80-2799-11e9-8162-0778e6fa766c.png)

**Comment by crcn** [comment]
Thanks for the catch! Issue's fixed and will go out in the next release today.

**Comment by crcn** [comment]
Here's the release: https://github.com/tandemcode/tandem/releases/tag/v10.1.31
