### ISSUE TITLE
Responsive layout tutorial

### ISSUE THREAD

**Issue by mapsgeek** [crcn/tandem-old#700]
i can't figure our my way around the app for building a full layout rather than individual components or how does tandem falls in the process of connecting these components we build in it, i think a proper tutorial or documentation would help

**Comment by crcn** [comment]
Let me know if this resolves any confusion: https://www.youtube.com/watch?v=bLONqLA2e1w&list=PLCNS_PVbhoSXOrjiJQP7ZjZJ4YHULnB2y&index=8&t=0s.

**Comment by mapsgeek** [comment]
thank you, it's defiantly a help and i hope we get more of this and more in depth videos on tandem as a workflow in design and development.

**Comment by crcn** [comment]
Are there any kinds of videos you'd like to see? I'd be happy to prioritize them.

**Comment by mapsgeek** [comment]
thank you for paying attention to this, i try to use tandem as a UI building tool just as what is written in the website "Just the view layer" i know that it's now has more to do with logic but at least until it supports something other than react, angular or vue integration, if there's a possibility to see more tutorials focused on designing UI and responsive layouts even if just a one in depth landing page video from scratch would be great for people who intend to use the app the way i described.
